### PR TITLE
Adding possibility to use month numbers.

### PR DESCRIPTION
**Pull request by 1313e**
Well, this is solely the changes to allow for month numbers to be used.

### CODE REVIEW

**Comment by 1313e** [comment]
I guess that some dependency broke the package somewhere between September 8 (5a218cfc2327c783d63fc6d3061a23cdebeb86f5) and December 25 (8e8b6669ae42923aa32d4a9bc6477dffdf591015), as the latter commit shows the exact same tests failing as this PR does.
Shall I request to merge it into [`new_paradigm`](https://github.com/pcubillos/bibmanager/tree/new_paradigm) instead?

**Comment by pcubillos** [comment]
Oh, yes please, work on the #new_paradigm branch, that's the dev branch at the moment (which I haven't merged yet). Sorry about that.

**Comment by 1313e** [comment]
@pcubillos There you go.
I think you have to manually restart the CI build for the PR.

**Comment by pcubillos** [comment]
Merged, thanks!

**Pull request merged**
